z_chat/urls.py
from django.urls import path
from .views import ChatView , GetOrCreatePrivateChat,ChatDelete,ChatEdit,chat_leave_view , CreateGroupChat, ChatFileUpload

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view() , name='home'),
    path('new-groupchat/', CreateGroupChat.as_view() , name='new-groupchat'),
    path('<username>' , GetOrCreatePrivateChat.as_view() , name="start-chat"),
    path('room/<chat_name>', ChatView.as_view() , name='chat-room'),
    path('room/<chat_name>/delete', ChatDelete.as_view() , name='chat-delete'),
    path('room/<chat_name>/edit', ChatEdit.as_view() , name='chat-edit'),
    path('room/<chat_id>/leave', chat_leave_view , name='chat-leave'),
    path('room/fileupload/<chat_name>', ChatFileUpload.as_view() , name='chat-file-upload'),
]

z_core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('z_home.urls' , namespace='home')),
    path('posts/', include('z_posts.urls' , namespace='posts')),
    path('users/', include('z_users.urls' , namespace='users')),
    path('chat/', include('z_chat.urls', namespace='chat')),
    path('comments/' , include('z_comments.urls' , namespace='comments')),
    path('video/' , include('z_videochat.urls' , namespace='videochat')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

z_posts/urls.py
from django.urls import path
from z_posts.views import PostCreate, PostList, PostInfo, PostDelete, PostEdit, PostLike

app_name = 'posts'

urlpatterns = [
    path('post-feed/', PostList.as_view(), name='post-feed'),
    path('post-create/', PostCreate.as_view(), name='post-create'),
    path('post-feed/<int:post_id>/info', PostInfo.as_view(), name='post-info'),
    path('post-feed/<int:post_id>/edit', PostEdit.as_view(), name='post-edit'),
    path('post-feed/<int:post_id>/delete', PostDelete.as_view(), name='post-delete'),
    path('post-feed/<int:post_id>/like', PostLike.as_view(), name='post-like'),
]

z_users/urls.py
from django.urls import path
from z_users.views import *

app_name = 'users'

urlpatterns = [
    path('profile/', UserProfile.as_view(), name='profile'),
    path('profile/<username>', UserProfile.as_view(), name='profile'),
    path('profile/edit/' , UserProfileEdit.as_view(), name="profile-edit"),
    path('profile/email-edit/' , UserProfileEditEmail.as_view(), name="profile-email-edit"),
    path('profile/<user_id>/clear-notifications/', ClearNotifications.as_view(), name='profile-clear-notifications' ),
    path('profile/<user_id>/notification/<notification_id>',ClearCurrentNotification.as_view(), name='profile-clear-current-notification')
]

z_users/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import User

from django.db.models.signals import post_save
from django.dispatch import receiver
from z_posts.models import Post
from cloudinary.models import CloudinaryField

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE, related_name='profile' )
    # image = models.ImageField(upload_to='avatars/', null=True, blank=True)
    image = CloudinaryField('image', null=True, blank=True, default='https://res.cloudinary.com/dsnftekpz/image/upload/v1734869367/q8cupwjicmns3t6iyhqp.jpg')
    info = models.CharField(max_length=300, blank=True, null=True)
    displayname = models.CharField(max_length=30, null=True, blank=True)


    def __str__(self):
        return f'{self.user}'
    
    @property
    def name(self):
        if self.displayname:
            return f'{self.displayname}'
        else:
            return f'{self.user.username}'
        
    
@receiver(post_save , sender=User)
def create_user_profile(sender , instance , created , **kwargs):
    if created:
        Profile.objects.create(user=instance, displayname=instance.username)

@receiver(post_save, sender=User)
def save_user_profile(sender , instance , **kwargs):
    instance.profile.save()

from django.db import models
from django.contrib.auth.models import User


class UserNotification(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sent_comment_notifications")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_notifications")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="+")
    body = models.CharField(max_length=256, blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    has_seen = models.BooleanField(default=False)

    def __str__(self):
        return f'from @{self.author} -> to @{self.receiver}'
    

z_users/forms.py
from django.contrib.auth.models import User
from django import forms
from z_users.models import Profile
from cloudinary.forms import CloudinaryFileField


class ProfileForm(forms.ModelForm):
    displayname = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Display Name', 'class':'form-control mb-2  mt-2  p-2'}))

    info = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows':3, 'placeholder': 'Info', 'class':'form-control mb-2  mt-2  p-2'}))

    # image = forms.ImageField(required=False, widget=forms.FileInput(attrs={'class':'form-control mb-2  mt-2  p-2 '}))
    image = CloudinaryFileField()
    class Meta:
        model = Profile
        fields = ['displayname' , 'image' , 'info' ]


class EmailForm(forms.ModelForm):
    email = forms.EmailField( widget=forms.EmailInput(attrs={ 'name':'email', 'id':'id_email', 'placeholder': 'Email', 'class':'form-control mb-2  mt-2  p-2'}))

    class Meta:
        model = User
        fields = ['email']

z_users/views.py
from django.urls import reverse_lazy
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import View
from .models import UserNotification
from django.shortcuts import  redirect, render
from django.contrib.auth.mixins import LoginRequiredMixin
from z_users.models import Profile
from z_users.forms import ProfileForm, EmailForm
from django.views.generic import DetailView
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import UserPassesTestMixin
# Create your views here.




class UserProfile(LoginRequiredMixin,DetailView):
    profile_model = Profile
    context_object_name = 'profile'
    template_name = 'users/profile_page.html'
    
    def get_object(self, queryset = False):
        current_profile = self.profile_model.objects.get(user__username=self.kwargs.get("username"))
        return current_profile
    
    
class UserProfileEdit(UserPassesTestMixin, LoginRequiredMixin, UpdateView):
    template_name = "users/profile_edit_page.html"
    form_class = ProfileForm
    model = Profile

    def test_func(self):
        return self.request.user == self.get_object().user
    
    def get_object(self, queryset = False):
        current_profile = self.model.objects.get(user=self.request.user) 
        return current_profile
    
    def get_success_url(self):
        return reverse_lazy('users:profile' , kwargs={'username':self.request.user.username})
    

class UserProfileEditEmail(LoginRequiredMixin, View):
    template_name = "users/profile_page.html"
    form_class = EmailForm
    user_model = User


    def post(self,request, *args, **kwargs):
        form = EmailForm(request.POST, instance=request.user)

        if form.is_valid():
            email = form.cleaned_data['email']

            if self.user_model.objects.filter(email=email).exclude(id=request.user.id).exists():
                return redirect('users:profile-edit')
            form.save()
        return redirect('users:profile' , username=request.user.username)
    
    def get(self, request, *args, **kwargs):
         if request.htmx:
            form = EmailForm(instance=request.user)
            return render(request, 'partials/email_form.html' , {'form':form})


class ClearNotifications(LoginRequiredMixin, View):
    user_notification_model = UserNotification

    def get(self, request, *args, **kwargs):
        user_id = self.kwargs['user_id']
        user = User.objects.get(id=user_id)
        user_notifications = self.user_notification_model.objects.filter(
            Q(receiver=user)|
            Q(has_seen=False)
        )
        

        for notification in user_notifications:
            notification.has_seen = True
            notification.save()

        return redirect(request.META.get('HTTP_REFERER'))


class ClearCurrentNotification(LoginRequiredMixin, View):
    notification_model = UserNotification
    
    def get(self,request, *args, **kwargs):
        notification_id = self.kwargs['notification_id']
        self.current_notification = self.notification_model.objects.get(id=notification_id)
        self.current_notification.has_seen = True
        self.current_notification.save()
        return redirect('posts:post-info', post_id = self.current_notification.post.id)
    
    def test_func(self):
        return self.request.user == self.current_notification.receiver
    
    
# @login_required
# def user_profile_view(request, username=None):

#     if username:
#         profile = get_object_or_404(User , username=username).profile
#         context = { 'profile':profile}
#     else:
#         profile = Profile.objects.get(user__username=request.user.username)
#         context = { 'profile':profile }

#     return render(request, "users/profile_page.html", context)




# def user_profile_edit_view(request):

#     form = ProfileForm(instance=request.user.profile)
#     profile = get_object_or_404( Profile , user = request.user) 

#     if request.method == "POST":
#         form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
#         if form.is_valid():
#             form.save()

#         context = {"form": form , 'profile':profile}
#         return redirect("users:profile")


#     context = {"form": form, 'profile':profile}
#     return render(request, "users/profile_edit_page.html", context)


#def user_profile_edit_email_view(request):
#     if request.htmx:
#         form  = EmailForm(instance=request.user)
#         return render(request , 'partials/email_form.html' , {'form':form})
    
#     if request.method == "POST":
#         form = EmailForm(request.POST, instance=request.user)

#         if form.is_valid():
#             email = form.cleaned_data['email']

#             if User.objects.filter(email=email).exclude(id=request.user.id).exists():
#                 return redirect('users:profile-edit')
#             form.save()
#         return redirect('users:profile')

#     return redirect('home:feed-page')

z_users/templates/users/notifications.html
{% comment %} 
{% if notification or notifications.count %}
    <ul class="absolute right-0 mt-2 py-2 w-48 bg-gray-800 z-999 rounded-md shadow-lg" x-show="open" @click.outside="open = false" @keydown.escape="open = false">
        <li><a 
            href="{% url 'users:profile-clear-notifications' request_user.id %}" 
            class="cursor-pointer block px-4 py-2 text-white hover:bg-gray-700"> clear notifications</a></li>
    </ul>
{% endif %} {% endcomment %}

<ul id="notifications-menu"  hx-swap-oob="afterbegin" 
 class="absolute top-[90px] right-0 mt-2 py-2 w-48 bg-gray-800 z-999 rounded-md shadow-lg" x-show="open" @click.outside="open = false" @keydown.escape="open = false">

    {% if notification and notification.receiver == user %}
    <li><a href="{% url "users:profile-clear-current-notification" notification.receiver.id notification.id %}" class="block px-4 py-2 text-white hover:bg-gray-700">
    {{notification.body}}
            </a></li>

        {% else %}
    
        {% for notification in notifications %}
            <li><a  href="{% url "users:profile-clear-current-notification" notification.receiver.id notification.id %}" class="block px-4 py-2 text-white hover:bg-gray-700">       
                {{notification.body}}
            </a></li>
        {% endfor %}
    {%endif%}
</ul>

<div id="dropdown-notification-status"   class="absolute top-[-5px]  left-[-5px] z-99">
    <style>а 
        @keyframes fadeIn {
            from {
                opacity: 0;
            }
            to {
                opacity: 1;
            }
        }
    </style>
    
    {% if  notifications.count > 0 or user_notifications.count > 0  %}
        <div style="animation: fadeIn 0.3s ease-in-out;" class="red-dot fade-in-up">
        </div>
    {% endif %}
</div>

z_users/templates/users/profile_edit_page.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a class=" mt-2 btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" href="{% url 'users:profile' profile.user.username %}">  Profile  </a>
</div>

    <div class='container'>
        <h1 class="  text-3xl font-bold  mb-6  mt-6 "> Profile Edit Page </h1>
        {% if profile.image %}
            <div class="flex flex-col flex-start items-start">
                <p> Current Image: </p>
                <img class="" width="100" height="100" src="{{ profile.image.url }}">
            </div>
        {% endif %}


        <form class="mt-5" method="post" action="{% url 'users:profile-edit' %}" enctype="multipart/form-data" >
            {% csrf_token %}
            {{ form}}
            <button class='btn btn-primary' type='submit'> Save edits </button>
        </form>
    </div>
{% endblock content %}

z_users/templates/users/profile_page.html
{% extends "base.html" %}

{% block content %}
<!-- component -->
<div class="container ">
  <a class=" mt-2 btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" href="{% url 'posts:post-feed' %}">  Feed  </a>
</div>
<section class="bg-gray-100">
    <div class="max-w-lg mx-auto my-10 bg-white rounded-lg shadow-md p-5">
        <div class="flex flex-col items-center juctify-center">
            {% if request.user == profile.user %}
              <a class=" block btn btn-primary mt-4" href="{% url 'users:profile-edit'%}"> Edit profile </a>
            {% else %}
                <a class="block btn btn-primary mt-4" href="{% url 'chat:start-chat' profile.user.username %}"> chat with {{profile.name}}</a>
            {% endif %}
        </div>
      <img class="w-32 h-32 rounded-full mt-3 border mx-auto" src="{% if profile.image%} {{profile.image.url}} {% endif %}" alt="Profile picture">
      {% load cloudinary %}


      <h2 class="text-center text-2xl font-semibold mt-3">{{profile.displayname}}</h2>
      <p class="text-center text-gray-600 mt-1">@{{profile.user.username}}</p>
      <div class="flex justify-center mt-5">
        {% if request.user == profile.user %}
            <div class="flex flex-row items-center">
                <p id="email-field" class="text-gray-600">{{ profile.user.email }}</p>
            
                <a id="email-edit" class=" cursor-pointer border-gray-300 px-2 border-bottom ml-2" 
                hx-get="{% url 'users:profile-email-edit' %} "
                hx-target="#email-field"
                hx-swap="innerHTML"
                >
                edit email</a>
            </div>
        {% endif %}
      </div>

      <div class="mt-5">
        <h3 class="text-xl font-semibold">Bio</h3>
        <p class="text-gray-600 mt-2">{{profile.info}}</p>
      </div>
    </div>
</section>
{% endblock content %}