z_chat/urls.py
from django.urls import path
from .views import ChatView , GetOrCreatePrivateChat,ChatDelete,ChatEdit,chat_leave_view , CreateGroupChat, ChatFileUpload

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view() , name='home'),
    path('new-groupchat/', CreateGroupChat.as_view() , name='new-groupchat'),
    path('<username>' , GetOrCreatePrivateChat.as_view() , name="start-chat"),
    path('room/<chat_name>', ChatView.as_view() , name='chat-room'),
    path('room/<chat_name>/delete', ChatDelete.as_view() , name='chat-delete'),
    path('room/<chat_name>/edit', ChatEdit.as_view() , name='chat-edit'),
    path('room/<chat_id>/leave', chat_leave_view , name='chat-leave'),
    path('room/fileupload/<chat_name>', ChatFileUpload.as_view() , name='chat-file-upload'),
]

z_core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('z_home.urls' , namespace='home')),
    path('posts/', include('z_posts.urls' , namespace='posts')),
    path('users/', include('z_users.urls' , namespace='users')),
    path('chat/', include('z_chat.urls', namespace='chat')),
    path('comments/' , include('z_comments.urls' , namespace='comments')),
    path('video/' , include('z_videochat.urls' , namespace='videochat')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

z_posts/urls.py
from django.urls import path
from z_posts.views import PostCreate, PostList, PostInfo, PostDelete, PostEdit, PostLike

app_name = 'posts'

urlpatterns = [
    path('post-feed/', PostList.as_view(), name='post-feed'),
    path('post-create/', PostCreate.as_view(), name='post-create'),
    path('post-feed/<int:post_id>/info', PostInfo.as_view(), name='post-info'),
    path('post-feed/<int:post_id>/edit', PostEdit.as_view(), name='post-edit'),
    path('post-feed/<int:post_id>/delete', PostDelete.as_view(), name='post-delete'),
    path('post-feed/<int:post_id>/like', PostLike.as_view(), name='post-like'),
]

z_users/urls.py
from django.urls import path
from z_users.views import *

app_name = 'users'

urlpatterns = [
    path('profile/', UserProfile.as_view(), name='profile'),
    path('profile/<username>', UserProfile.as_view(), name='profile'),
    path('profile/edit/' , UserProfileEdit.as_view(), name="profile-edit"),
    path('profile/email-edit/' , UserProfileEditEmail.as_view(), name="profile-email-edit"),
    path('profile/<user_id>/clear-notifications/', ClearNotifications.as_view(), name='profile-clear-notifications' ),
    path('profile/<user_id>/notification/<notification_id>',ClearCurrentNotification.as_view(), name='profile-clear-current-notification')
]

z_chat/models.py
import os
from django.db import models
from django.contrib.auth.models import User
import shortuuid
from cloudinary.models import CloudinaryField

# Create your models here.
class Chat(models.Model):
    chat_name = models.CharField(max_length=128 , unique=True, blank=True)
    users_online = models.ManyToManyField(User , related_name='online_chat' , blank=True )
    members = models.ManyToManyField(User , related_name="member_in_chat", blank=True)
    group_chat_name = models.CharField(max_length=128 , blank=True , null=True)
    is_private = models.BooleanField(default=False)
    admin = models.ForeignKey(User, on_delete=models.CASCADE , related_name="admin_in_chat", blank=True, null=True)

    def __str__(self):
        if self.group_chat_name:
            return f'{self.group_chat_name}'
        elif self.is_private:
            return f'{self.members.all()[0].username} --- {self.members.all()[1].username}'
        else:
            return self.chat_name
        
    def save(self, *args, **kwargs):
        if not self.chat_name:
            self.chat_name = shortuuid.uuid()
        super().save(*args, **kwargs)
    
class ChatMessage(models.Model):
    chat = models.ForeignKey(Chat , on_delete=models.CASCADE, related_name="messages")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.CharField(max_length=256 , blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    image = CloudinaryField("image" , blank=True , null=True , resource_type="auto")

    def __str__(self):
        return f'{self.author}: {self.body}'
        
    
    @property
    def is_image(self):
        if self.filename.lower().endswith(('.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp')):
            return True
        else:
            return False

    class Meta:
        ...
        # ordering = ['-created']

z_chat/forms.py
from django import forms
from django.forms import widgets
from .models import ChatMessage , Chat
from cloudinary.forms import CloudinaryFileField

class ChatMessageForm(forms.ModelForm):
    body = forms.CharField(max_length=256 , widget=forms.TextInput(attrs={ "placeholder":"Write your message!" ,"class":"w-full focus:outline-none focus:placeholder-gray-400 text-gray-600 placeholder-gray-600 pl-12 bg-gray-200 rounded-md py-3",'autofocus':True }))
    image = CloudinaryFileField('image')
    class Meta:
        model = ChatMessage
        fields = ['body','image']


class GroupChatForm(forms.ModelForm):
    group_chat_name = forms.CharField(max_length=256 , widget=forms.TextInput(attrs={ 'type':'text' ,'name':"message", "placeholder":"Type your chat name...", "class":"w-full px-4 py-2 rounded-lg border border-gray-200 focus:outline-none" ,'autofocus':True }))

    class Meta:
        model = Chat
        fields = ['group_chat_name']


class ChatEditForm(forms.ModelForm):
    group_chat_name = forms.CharField(max_length=128 , widget=forms.TextInput(attrs={ 'type':'text' ,'name':"message", "placeholder":"Type your chat name...", "class":"w-full px-4 py-2 rounded-lg border border-gray-200 focus:outline-none" }))
    class Meta:
        model = Chat
        fields = ['group_chat_name']

z_chat/views.py
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import DeleteView, UpdateView, CreateView , View
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .models import Chat, ChatMessage
from .forms import ChatMessageForm, GroupChatForm , ChatEditForm
from django.http import Http404, HttpResponse
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

class ChatView(LoginRequiredMixin, View):
    template_name = 'chat/chat.html'
    form_class = ChatMessageForm

    def get(self, request, *args, **kwargs):
        self.chat_name = self.kwargs.get('chat_name' , 'public-chat')

        self.chat = get_object_or_404(Chat , chat_name = self.chat_name)

        other_user = None

        if self.chat.group_chat_name:
            self.chat_messages = self.chat.messages.all().reverse()[:30]

        elif self.chat.is_private:
            self.chat_messages = self.chat.messages.all().reverse()[:30]

        else:
            self.chat_messages = self.chat.messages.all().order_by('-created')[:30][::-1]
        
        if self.chat.is_private:
            if request.user not in self.chat.members.all():
                raise Http404()
            for member in self.chat.members.all():
                if member != request.user:
                    other_user = member
                    break

        if self.chat.group_chat_name:
            if request.user not in self.chat.members.all():
                self.chat.members.add(request.user)
        
        context = {
            'chat_messages': self.chat_messages,
            'form':self.form_class,
            'chat_name':self.chat_name,
            'chat':self.chat,
        }

        return render(request, 'chat/chat.html', context)

    def post(self, request, *args, **kwargs):
        form = ChatMessageForm()

        if request.htmx:
            form = ChatMessageForm(request.POST)
            if form.is_valid():
                message = form.save(commit=False)
                message.author = request.user
                message.chat = self.chat
                message.save()

                context = {
                    'message':message,
                    'user':request.user
                }
                return render(request, 'chat/partials/chat_message.html' , context)


class GetOrCreatePrivateChat(LoginRequiredMixin , View):
    template_name = 'users/profile_page.html'
    user_model = User

    def get(self,request, *args , **kwargs):
        username = self.kwargs.get('username')

        if request.user.username == username:
            return redirect('chat:home')
        
        other_user = get_object_or_404(User , username=username)
        my_chats =  request.user.member_in_chat.filter(is_private=True)

        if my_chats.exists():
            for my_chat in my_chats:
                if other_user in my_chat.members.all():
                    return redirect('chat:chat-room' , chat_name=my_chat.chat_name)
        
        chat = Chat.objects.create(is_private=True)
        chat.members.add(request.user, other_user)
        return redirect('chat:chat-room' , chat_name=chat.chat_name)
        
class CreateGroupChat( LoginRequiredMixin, CreateView):
    form_class = GroupChatForm
    template_name = 'chat/create_group_chat.html'
    chat_model = Chat

    def form_valid(self, form):
        chat_name = self.request.POST.get('group_chat_name')
        chat_exists = self.chat_model.objects.filter(group_chat_name=chat_name).exclude(
                Q(is_private='True')|
                Q(chat_name='public-chat')|
                Q(chat_name='online-status')
            )

        if chat_exists.exists():
            return redirect('chat:chat-room' , chat_name=chat_exists[0].chat_name)
        else:
            self.chat = form.save(commit=False)
            self.chat.admin = self.request.user
            self.chat.save()
            self.chat.members.add(self.request.user)
            self.chat.save()
            return super().form_valid(form)
    
    def get_success_url(self):
        chat_name = self.chat.chat_name
        return reverse_lazy('chat:chat-room', kwargs={"chat_name":chat_name})


class ChatDelete(UserPassesTestMixin, LoginRequiredMixin , DeleteView):
    chat_model = Chat
    template_name = 'chat/chat_delete.html'
    context_object_name = 'chat'

    def get_object(self , queryset = None):
        chat_name = self.kwargs.get('chat_name')
        chat = get_object_or_404(self.chat_model, chat_name=chat_name)
        return chat

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return redirect('chat:home')

    def test_func(self):
        current_chat = self.get_object()
        current_user = self.request.user
        return current_chat.admin == current_user


class ChatEdit(UserPassesTestMixin, LoginRequiredMixin , UpdateView):
    chat_model = Chat
    template_name = 'chat/chat_edit.html'
    context_object_name = 'chat'
    form_class = ChatEditForm

    def get_object(self, queryset =None):
        chat_name = self.kwargs.get('chat_name')
        current_chat = get_object_or_404(self.chat_model , chat_name=chat_name)
        return current_chat
    
    def post(self, request, *args, **kwargs):
        chat = self.get_object()

        form = ChatEditForm(request.POST , instance=chat)
        if form.is_valid():
            members = request.POST.getlist('members')
            form.save()
            for member_id in members:
                member_user = User.objects.get(id=member_id)
                chat.members.remove(member_user)

            return redirect('chat:chat-room', chat_name=chat.chat_name)

    def test_func(self):
        current_chat = self.get_object()
        current_user = self.request.user
        return current_chat.admin == current_user


@login_required
def chat_leave_view(request, chat_id):
    chat = Chat.objects.get(id=chat_id)
    chat.members.remove(request.user)
    return redirect('chat:home')


class ChatFileUpload(LoginRequiredMixin , View):
    chat_message_model = ChatMessage
    def post(self, request, *args, **kwargs):
        chat = get_object_or_404(Chat , chat_name = self.kwargs.get('chat_name'))
        if request.htmx and request.FILES:
            image = request.FILES['image']

            message = self.chat_message_model.objects.create(
                chat=chat,
                author=request.user,
                image=image,
            )

            cnannel_layer = get_channel_layer()
            event={
                'type':'chat_message_handler',
                'message_id':message.id,
            }
            async_to_sync(cnannel_layer.group_send)(
                chat.chat_name , event
            )
        return HttpResponse()

# def chat_view(request, chat_name = 'public-chat'):
    # chat = get_object_or_404(Chat , chat_name = chat_name)

    # other_user = None

    # if chat.group_chat_name:
    #     chat_messages = chat.messages.all().reverse()[:30]
    # elif chat.is_private:
    #     chat_messages = chat.messages.all().reverse()[:30]
    # else:
    #     chat_messages = chat.messages.all().reverse()[:30]
    
    # if chat.is_private:
    #     if request.user not in chat.members.all():
    #         raise Http404()
    #     for member in chat.members.all():
    #         if member != request.user:
    #             other_user = member
    #             break

    # if chat.group_chat_name:
    #     if request.user not in chat.members.all():
    #         chat.members.add(request.user)

    # form = ChatMessageForm()

    # if request.htmx:
    #     form = ChatMessageForm(request.POST)
    #     if form.is_valid():
    #         message = form.save(commit=False)
    #         message.author = request.user
    #         message.chat = chat
    #         message.save()

    #         context = {
    #             'message':message,
    #             'user':request.user
    #         }
    #         return render(request, 'chat/partials/chat_message.html' , context)
        
    # context = {
    #     'chat_messages': chat_messages,
    #     'form':form,
    #     'chat_name':chat_name,
    #     'chat':chat,
    # }

    # return render(request, 'chat/chat.html', context)

# def chat_edit_view(request, chat_name):
#     chat = get_object_or_404(Chat, chat_name=chat_name)
#     form = ChatEditForm(instance=chat)

#     if request.method == "POST":
#         form = ChatEditForm(request.POST , instance=chat)
#         if form.is_valid():
#             members = request.POST.getlist('members')
#             form.save()
#             for member_id in members:
#                 member_user = User.objects.get(id=member_id)
#                 chat.members.remove(member_user)

#             return redirect('chat:chat-room', chat_name=chat.chat_name)

#     context = {
#         'form':form,
#         'chat':chat
#     }

#     return render (request, 'chat/chat_edit.html' , context)


# def chat_delete_view(request, chat_name):
#     chat = get_object_or_404(Chat , chat_name=chat_name)

#     if request.method == "POST":
#         if request.user == chat.admin:
#             chat.delete()
#             return redirect('chat:home')
#     context = {'chat' : chat}

#     return render(request, 'chat/chat_delete.html', context)

# def get_or_create_chat(request , username):
#     if request.user.username == username:
#         return redirect('chat:home')
        
#     other_user = get_object_or_404(User , username=username)
#     my_chats =  request.user.member_in_chat.filter(is_private=True)

#     if my_chats.exists():
#         for my_chat in my_chats:

z_chat/templates/chat/chat.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <a class=" mt-2 btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" href="{% url 'posts:post-feed' %}">  Feed  </a>
</div>
<!-- component -->
<div class="container bg-white mt-4 flex-1 p:2 sm:p-6 justify-between flex flex-col h-[90vh]">
    <div class="flex sm:items-center justify-between py-3 border-b-2 border-gray-200">

       <div id="online_in_chat">online</div> 
       {% if chat.admin == request.user  %}
        <a  class="btn btn-primary" href=" {% url 'chat:chat-edit' chat.chat_name %} ">
            Edit chat
        </a>
        {% else %}
            {% if chat.group_chat_name %}
                <a class="btn btn-danger" href="{% url 'chat:chat-leave' chat.id %}"> Leave chat </a>
            {% endif %}
        {% endif%}
        </div>



    <div id="chat_messages" class="flex flex-col space-y-4 p-3 overflow-y-auto scrollbar-thumb-blue scrollbar-thumb-rounded scrollbar-track-blue-lighter scrollbar-w-2 scrolling-touch">
        
        {% for message in chat_messages %}
            {% include "chat/message.html" %}
        {% endfor %}   

    </div>


<form method="post" enctype="multipart/form-data"
    id='file_upload'
    hx-post="{% url 'chat:chat-file-upload' chat_name %}"
    hx-target="#chat_messages"
    hx-swap="beforeend"
    _="on htmx:afterRequest reset() me"
    >
    {% csrf_token %}
    {{form.image}}
     <label  for="id_image" type="button" class="inline-flex items-center justify-center rounded-full h-10 w-10 transition duration-500 ease-in-out text-gray-500 hover:bg-gray-300 focus:outline-none">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6 text-gray-600">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"></path>
        </svg>
        </label>

        <button id="submit_file_btn" class="bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" type="submit"> Send file</button>
</form>
<div class="border-t-2 border-gray-200 px-4 pt-4 mb-2 sm:mb-0">

<form 
        hx-ext="ws"
        ws-connect="/ws/chat/{{chat_name}}"
        ws-send
        _="on htmx:wsAfterSend reset() me"
        class="relative flex">
         {{form.body}}
          <div class=" right-0 items-center inset-y-0  flex flex-row   ">
                <button type="submit" class="inline-flex items-center justify-center rounded-lg px-2 py-3 transition duration-500 ease-in-out text-white bg-blue-500 hover:bg-blue-400 focus:outline-none">
                    <span class="font-bold">Send</span>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="h-6 w-6 ml-2 transform rotate-90">
                       <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z"></path>
                    </svg>
                 </button>
          </div>
</form>

    </div>
</div>
 
 <style>
    .scrollbar-w-2::-webkit-scrollbar {
    width: 0.25rem;
    height: 0.25rem;
    }
    
    .scrollbar-track-blue-lighter::-webkit-scrollbar-track {
    --bg-opacity: 1;
    background-color: #f7fafc;
    background-color: rgba(247, 250, 252, var(--bg-opacity));
    }
    
    .scrollbar-thumb-blue::-webkit-scrollbar-thumb {
    --bg-opacity: 1;
    background-color: #edf2f7;
    background-color: rgba(237, 242, 247, var(--bg-opacity));
    }
    
    .scrollbar-thumb-rounded::-webkit-scrollbar-thumb {
    border-radius: 0.25rem;
    }
 </style>

 {% endblock content %}

{% block javascript %} 
 <script>
     function scrollToBottom(){
        var elem = document.getElementById('chat_messages');
        elem.scrollTop = elem.scrollHeight;
    }
    scrollToBottom();

        function toggleSubmitButton(){
            var input = document.getElementById('id_image');
            input.classList.add("hidden");

            var submitButton = document.getElementById("submit_file_btn");
            submitButton.classList.add("hidden");            
            var form = document.getElementById("file_upload");

            form.addEventListener('submit', async function() {
                submitButton.classList.add("hidden");
            });
            


            input.addEventListener('change', function() {
                if (input.files.length > 0) {
                    submitButton.classList.remove("hidden");
                } else {
                    submitButton.classList.add("hidden");
                }
            });
        }
        
        toggleSubmitButton(); 
    </script>
    
    

{% endblock javascript %}

z_chat/templates/chat/chat_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1 class="text-3xl text-center mt-5 text-red-500 ">Chat deleted</h1>

        <form method="post" action=" {% url "chat:chat-delete" chat.chat_name %}">
            {% csrf_token%}

            <p>Are you shoure that you want to delete <b>{{ chat.group_chat_name }}</b> ? </p>
            <button class="btn btn-danger" type="submit">
                delete chat
            </button>
        </form>


    </div>
{% endblock content %}  

z_chat/templates/chat/chat_edit.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-3xl text-center mt-5 text-green-800 ">Edit profile</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="text-lg mt-4"> Choos members that you want to delete from chat </div>
        {% for member in chat.members.all %}
            {% if member.id != chat.admin.id %}
                <div class="flex items-center gap-2 py-2">
                    <input type="checkbox" name="members" value="{{member.id}}" id="{{member.id}}">
                    <label class="text-lg" for="{{member.id}}"> {{member.profile.name}} </label>
                </div>
            {% endif %}
        {% endfor %}
        <button class="btn btn-primary" type="submit"> save changes </button>
    </form>
    <a class="btn btn-danger mt-4" href="{% url 'chat:chat-delete' chat.chat_name%}"> Delete chat</a>
</div>
{% endblock content%}

z_chat/templates/chat/create_group_chat.html
{% extends "base.html" %}

{% block content %}
    <div class="conteiner mx-auto">
        <h1 class="text-3xl text-center mt-5"> Create group chat </h1>
    <form  class="flex flex-col mx-auto  w-[calc(100vh-25rem)]" action="{% url "chat:new-groupchat" %}" method="post">
        {% csrf_token %}
        <div class="mt-4">
            {{form.group_chat_name}}
        </div>
        <button type="submit" class=" mt-3 flex items-center block justify-center px-4 py-2 rounded-lg bg-blue-500 text-white">create</button>
    </form>
</div>
{% endblock content%}

z_chat/templates/chat/message.html
{% if message.author == user %} 

    <div class="chat-message">
        <div class="flex items-end justify-end">
        <div class="flex flex-col space-y-2 text-sm max-w-xs mx-2 order-1 items-end">

            {% if message.body %}
            <div><span class="px-4 py-2 rounded-lg inline-block rounded-br-none bg-blue-600 text-white ">{{message.body}}
            </span></div>
            {% endif %}
            {% if message.image %}
                <img class="max-w-72 min-w-8" src="{{message.image.url}}" alt="image">
            {% endif%}
        </div>
        <img src="{{message.author.profile.image.url}}" class="w-12 h-12 rounded-full order-2">
        </div>
    </div>

 {% else %}

    <div class="chat-message">
        <div class="flex items-end">
        <div class="flex flex-col space-y-2 text-sm max-w-xs mx-2 order-2 items-start">
            <a href="{% url 'users:profile' message.author.username %}" class="font-semibold text-gray-700 text-xs ">@{{message.author.profile.name}}</a>

            {% if message.body %}
            <div><span class="px-4 py-2 rounded-lg inline-block bg-gray-300 text-gray-600 ">{{message.body}}</span></div>
            {% endif %}
            {% if message.image %}
                    <img class="max-w-72 min-w-8" src="{{message.image.url}}" alt="image">
            {% endif%}
            
        </div>
        <img src="{%if message.author.profile.image%} {{message.author.profile.image.url}}{% endif %}" class="w-12 h-12 rounded-full order-1">
        </div>
    </div>

 {% endif %}