z_chat/urls.py
from django.urls import path
from .views import ChatView , GetOrCreatePrivateChat,ChatDelete,ChatEdit,chat_leave_view , CreateGroupChat, ChatFileUpload

app_name = 'chat'

urlpatterns = [
    path('', ChatView.as_view() , name='home'),
    path('new-groupchat/', CreateGroupChat.as_view() , name='new-groupchat'),
    path('<username>' , GetOrCreatePrivateChat.as_view() , name="start-chat"),
    path('room/<chat_name>', ChatView.as_view() , name='chat-room'),
    path('room/<chat_name>/delete', ChatDelete.as_view() , name='chat-delete'),
    path('room/<chat_name>/edit', ChatEdit.as_view() , name='chat-edit'),
    path('room/<chat_id>/leave', chat_leave_view , name='chat-leave'),
    path('room/fileupload/<chat_name>', ChatFileUpload.as_view() , name='chat-file-upload'),
]

z_core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('admin/', admin.site.urls),
    path('', include('z_home.urls' , namespace='home')),
    path('posts/', include('z_posts.urls' , namespace='posts')),
    path('users/', include('z_users.urls' , namespace='users')),
    path('chat/', include('z_chat.urls', namespace='chat')),
    path('comments/' , include('z_comments.urls' , namespace='comments')),
    path('video/' , include('z_videochat.urls' , namespace='videochat')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

z_posts/urls.py
from django.urls import path
from z_posts.views import PostCreate, PostList, PostInfo, PostDelete, PostEdit, PostLike

app_name = 'posts'

urlpatterns = [
    path('post-feed/', PostList.as_view(), name='post-feed'),
    path('post-create/', PostCreate.as_view(), name='post-create'),
    path('post-feed/<int:post_id>/info', PostInfo.as_view(), name='post-info'),
    path('post-feed/<int:post_id>/edit', PostEdit.as_view(), name='post-edit'),
    path('post-feed/<int:post_id>/delete', PostDelete.as_view(), name='post-delete'),
    path('post-feed/<int:post_id>/like', PostLike.as_view(), name='post-like'),
]

z_users/urls.py
from django.urls import path
from z_users.views import *

app_name = 'users'

urlpatterns = [
    path('profile/', UserProfile.as_view(), name='profile'),
    path('profile/<username>', UserProfile.as_view(), name='profile'),
    path('profile/edit/' , UserProfileEdit.as_view(), name="profile-edit"),
    path('profile/email-edit/' , UserProfileEditEmail.as_view(), name="profile-email-edit"),
    path('profile/<user_id>/clear-notifications/', ClearNotifications.as_view(), name='profile-clear-notifications' ),
    path('profile/<user_id>/notification/<notification_id>',ClearCurrentNotification.as_view(), name='profile-clear-current-notification')
]

z_posts/models.py
from django.contrib.auth.models import User
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
from cloudinary.models import CloudinaryField
# Create your models here.


class Post(models.Model):
    body = CKEditor5Field('body', config_name='extends')
    # image = models.ImageField(upload_to='post_images' ,  null=True , blank=True)
    image = CloudinaryField('image', null=True, blank=True)

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")

    likes = models.ManyToManyField(User , related_name="liked_posts" , blank=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.author} - {self.body[:15]}'

    class Meta:
        ordering = ['-created']

z_posts/forms.py
from django import forms
from django.forms import widgets
from .models import Post
from django_ckeditor_5.widgets import CKEditor5Widget
from cloudinary.forms import CloudinaryFileField


class PostForm(forms.ModelForm):
    # image = forms.ImageField( required=False )
    image = CloudinaryFileField( required=False )

    class Meta:
        model = Post
        fields = ['body' , 'image']
        widgets= {
            'body': CKEditor5Widget(
                  attrs={"class": "django_ckeditor_5"}, config_name="comment"
              )
          }
        

z_posts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, View , ListView

from z_users.models import  UserNotification
from .models import Post
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from .forms import PostForm
from z_comments.forms import CommentForm
from z_comments.models import Comment
# Create your views here.


class PostList(ListView):
    paginate_by = 5
    template_name = "posts/post_list.html"
    context_object_name = "posts" 
    allow_empty = True

    def get_context_data(self, **kwargs) :
        context = super().get_context_data(**kwargs)
        return context
    
    def get_queryset(self):
        return Post.objects.all()
    

class PostInfo(LoginRequiredMixin, DetailView):
    post_model = Post
    comments_model = Comment
    template_name = "posts/post_info.html"
    context_object_name = "post"
    form_class = CommentForm

    def get_object(self, queryset = None):
        post_id = self.kwargs.get("post_id")
        current_post = self.post_model.objects.get(id=post_id)
        return current_post
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = self.form_class
        context['comments'] = self.get_object().comments.all().order_by('created')
        return context


class PostDelete( LoginRequiredMixin, UserPassesTestMixin , DeleteView):
    model = Post
    template_name = "posts/post_delete.html"
    success_url = reverse_lazy("posts:post-feed")
    
    def get_object(self, queryset = False):
        post_id = self.kwargs.get("post_id")
        current_post = self.model.objects.get(id=post_id)
        return current_post
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if isinstance(self.object, self.model):
            self.object.delete()
            return HttpResponseRedirect(self.get_success_url())
        
    def test_func(self):
        post_id = self.kwargs.get("post_id")
        current_post = self.model.objects.get(id=post_id)
        return self.request.user == current_post.author


class PostEdit(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post 
    form_class = PostForm
    template_name = "posts/post_edit.html"
    
    def get_object(self, queryset = False):
        post_id = self.kwargs.get("post_id")
        current_post = self.model.objects.get(id=post_id)
        return current_post
    
    def get_success_url(self):
        return reverse_lazy('posts:post-info', kwargs = {'post_id': self.kwargs.get('post_id')})
    
    def test_func(self):
        post = self.get_object()
        return self.request.user == post.author
        

class PostCreate(LoginRequiredMixin , CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_create.html"


    def get_success_url(self):
        return reverse_lazy('posts:post-info' , kwargs = {'post_id': self.post.id})
    
    def form_valid(self, form):
        self.post = form.save(commit=False)
        self.post.author = self.request.user
        self.post.save()
        return super().form_valid(form)


class PostLike(LoginRequiredMixin , View):
    post_model = Post
    user_notification_model = UserNotification
    def get(self, request, *args, **kwargs):
       
        post_id = self.kwargs.get("post_id")
        current_user = request.user
        current_post = self.post_model.objects.get(id=post_id)


        if current_user in current_post.likes.all():
            current_post.likes.remove(current_user)
            if current_post.author != current_user:
                self.user_notification_model.objects.filter(post = current_post).delete()
        else:       
            current_post.likes.add(current_user)
            if current_post.author != current_user:
                self.user_notification_model.objects.create(
                author = current_user,
                receiver = current_post.author,
                post = current_post,
                body = f'{current_user} liked your post'
        )


        

        if  request.htmx:
            return render(request, "partials/like_count.html" , {'post':current_post})
            

z_posts/templates/posts/post_create.html
{% extends "base.html" %}



{% block content %}
    <div class="container mx-auto max-w-xl mt-5">
        <div class="bg-gray-100 border border-gray-300 rounded-lg shadow-md">
            <div class="p-4">
                <h1 class="text-xl font-bold text-gray-800 mb-4">Crete Post</h1>
                <form method="post" enctype="multipart/form-data" class="space-y-4">
                    {% csrf_token %}
                    {{form.as_p}}
                    {{ form.media }}
                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-400 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-full">Create post </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

z_posts/templates/posts/post_delete.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-6">
            <div class="card shadow">   
                <div class="card-body text-center">
                    <h1 class="card-title mb-4">Delete Post</h1>
                    <p class="lead mb-4">Are you sure you want to delete this post?</p>
                    <form method="POST">
                        {%csrf_token%}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%} 

z_posts/templates/posts/post_edit.html
{% extends "base.html" %}
{% block content %}
    <div class="container mx-auto max-w-xl mt-5">
        <div class="bg-gray-100 border border-gray-300 rounded-lg shadow-md">
            <div class="p-4">
                <h1 class="text-xl font-bold text-gray-800 mb-4">Edit Post</h1>
                <form method="post" enctype="multipart/form-data" class="space-y-4">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="flex justify-end">
                        <button type="submit" class="bg-blue-400 hover:bg-blue-600 text-white font-semibold py-2 px-4 rounded-full">Save Changes</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

z_posts/templates/posts/post_info.html
{% extends "base.html" %}
{%block content%}
<div class="container">
        <a class=" mt-2 btn bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full" href="{% url 'posts:post-feed' %}">  Feed  </a>
</div>
<div class=" rounded shadow-md p-2 container mt-5 mx-auto h-[calc(100vh-10rem)]  bg-white  shadow-none">
    
    <div class=" flex min-[500px]:flex-col lg:flex-row sm:flex-col xs:flex-col gap-20 ">
        {% if post.image %}  
            <div class="flex-1 pb-10 lg:h-[calc(100vh-11rem)] xl:h-[calc(100vh-11rem)] md:h-[calc(100vh-11rem)]  overflow-hidden flex flex-col items-center justify-center ">
                <img class="w-[90%]  object-fill"
                    src="{{post.image.url}}"
                    alt="Description">
            </div>
        {% endif %}

        {%if not post.image %} 
            <div class=" flex-2  ">
        {% else %}
            <div class="  ">
        {% endif %}  

            <header class="border-b pb-2 border-grey-400">
                <div class="flex flex-row items-center justify-between">
                    <div>
                        <a href="{% url 'users:profile' post.author.username %}" class="block cursor-pointer py-4 flex items-center text-md outline-none focus:outline-none focus:border-gray-300 transition duration-150 ease-in-out">
                            <img src="{%if post.author.profile.image %}{{post.author.profile.image.url}}{%endif%}" class="h-9 w-9 rounded-full object-cover"
                            alt="user" />
                            <p class="block ml-2 font-bold">{{post.author.profile.displayname}}</p>
                        </a>
                    </div>
                {% if post.author == user %}
                    <div class="mr-4 flex flex-row gap-4">
                        <div class="">
                            <a href="{% url 'posts:post-delete' post.id%}">
                            <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 30 30">
                                <path d="M 14.984375 2.4863281 A 1.0001 1.0001 0 0 0 14 3.5 L 14 4 L 8.5 4 A 1.0001 1.0001 0 0 0 7.4863281 5 L 6 5 A 1.0001 1.0001 0 1 0 6 7 L 24 7 A 1.0001 1.0001 0 1 0 24 5 L 22.513672 5 A 1.0001 1.0001 0 0 0 21.5 4 L 16 4 L 16 3.5 A 1.0001 1.0001 0 0 0 14.984375 2.4863281 z M 6 9 L 7.7929688 24.234375 C 7.9109687 25.241375 8.7633438 26 9.7773438 26 L 20.222656 26 C 21.236656 26 22.088031 25.241375 22.207031 24.234375 L 24 9 L 6 9 z"></path>
                            </svg>
                            </a>
                        </div>
                        <div>
                            <a href="{% url 'posts:post-edit' post.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="20" height="20" viewBox="0 0 50 50">
                                    <path d="M 43.125 2 C 41.878906 2 40.636719 2.488281 39.6875 3.4375 L 38.875 4.25 L 45.75 11.125 C 45.746094 11.128906 46.5625 10.3125 46.5625 10.3125 C 48.464844 8.410156 48.460938 5.335938 46.5625 3.4375 C 45.609375 2.488281 44.371094 2 43.125 2 Z M 37.34375 6.03125 C 37.117188 6.0625 36.90625 6.175781 36.75 6.34375 L 4.3125 38.8125 C 4.183594 38.929688 4.085938 39.082031 4.03125 39.25 L 2.03125 46.75 C 1.941406 47.09375 2.042969 47.457031 2.292969 47.707031 C 2.542969 47.957031 2.90625 48.058594 3.25 47.96875 L 10.75 45.96875 C 10.917969 45.914063 11.070313 45.816406 11.1875 45.6875 L 43.65625 13.25 C 44.054688 12.863281 44.058594 12.226563 43.671875 11.828125 C 43.285156 11.429688 42.648438 11.425781 42.25 11.8125 L 9.96875 44.09375 L 5.90625 40.03125 L 38.1875 7.75 C 38.488281 7.460938 38.578125 7.011719 38.410156 6.628906 C 38.242188 6.246094 37.855469 6.007813 37.4375 6.03125 C 37.40625 6.03125 37.375 6.03125 37.34375 6.03125 Z"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                    {% endif %}
                </div>

                <div>{{post.body|safe}}</div>

            </header>
            <div class=" bg-white ">
                <div >
                    <div id="comments_container" class="pt-1 h-[calc(100vh-29rem)]  overflow-y-auto ">
                        {% for comment in comments %}
                            {% include "partials/comment_inner.html" %}
                        {% endfor %}
                    </div>
                </div>

                <div class="">
                    <div class="pt-4">
                        <div class="mb-2">
                            <div class="flex items-center">
                                <a 
                                    hx-get="{% url 'posts:post-like' post.id %}"
                                    hx-target="#like_count"
                                    hx-swap="innerHTML"
                                    class="mr-3 inline-flex items-center cursor-pointer">
                                    <svg class="fill-heart text-gray-700 inline-block h-7 w-7 heart" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z" />
                                    </svg>
                                </a>
                                <span class="mr-3 inline-flex items-center cursor-pointer">
                                    <svg class="text-gray-700 inline-block h-7 w-7 " xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                                    </svg>
                                </span>
                            </div>
                            <span id="like_count" class="text-gray-600 text-sm font-bold">{{post.likes.count}} Likes</span>
                        </div>
                        <span class="block ml-2 text-xs text-gray-600">{{post.created}}</span>
                    </div>
                    
                    <div class="pt-4 pb-1 pr-3">
                        <div class="flex items-start">
                            {% include "components/comment_form.html" %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script>
    function scrollToBottomComments(){
        var elem = document.getElementById('comments_container');
        elem.scrollTop = elem.scrollHeight;
    }
    scrollToBottomComments();
</script>
{% endblock javascript %}

z_posts/templates/posts/post_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mx-auto  ">
        <div class="flex flex-col items-center mt-5">
            <a href="{% url "posts:post-create"%} ">
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">Create Post</button>
            </a>
        </div>    
        <div class="flex flex-col">
            {% for post in posts %}
            {% include "components/post_item.html" %}
            {% endfor %} 
        </div>
        <div class="flex justify-center">
            {% include "components/pagination.html" %}
        </div>
</div>
{% endblock content %}